■初期化パラメータ(nls_length_semantics)
SELECT NAME,VALUE FROM V$SYSTEM_PARAMETER WHERE NAME = 'nls_length_semantics'

■カラム情報
SELECT 
  A.TABLE_NAME,
  A.COLUMN_ID,
  A.COLUMN_NAME,
  A.DATA_TYPE,
  CASE
    WHEN C.CONSTRAINT_TYPE='P' THEN 'Y'
    ELSE 'N'
  END AS PRIMARY_KEY,
  A.NULLABLE,
  CASE
    WHEN C.CONSTRAINT_TYPE='P' OR A.DATA_TYPE NOT IN ('VARCHAR2','NVARCHAR2','CHAR','NCHAR','NUMBER','BINARY_FLOAT','BINARY_DOUBLE') THEN 'Y'
    ELSE 'N'
  END AS READ_ONLY,
  A.DATA_LENGTH,
  A.CHAR_COL_DECL_LENGTH,
  A.DATA_PRECISION,
  A.DATA_SCALE,
  CASE
    WHEN A.DATA_TYPE IN ('VARCHAR2','NVARCHAR2') THEN GREATEST(LEAST(A.CHAR_COL_DECL_LENGTH,15),5)
    WHEN A.DATA_TYPE IN ('NUMBER','BINARY_FLOAT','BINARY_DOUBLE') THEN GREATEST(A.DATA_PRECISION,15)
    ELSE 15
  END AS COLUMN_WIDTH,
  B.COMMENTS,
  CASE
    WHEN A.DATA_TYPE IN ('CHAR','NCHAR') THEN '文字（固定長）'
    WHEN A.DATA_TYPE IN ('VARCHAR2','NVARCHAR2') THEN '文字（可変長）'
    WHEN A.DATA_TYPE IN ('NUMBER','BINARY_FLOAT','BINARY_DOUBLE') THEN '数値'
    WHEN A.DATA_TYPE='DATE' OR SUBSTR(A.DATA_TYPE,0,9)='TIMESTAMP' THEN '日付'
    ELSE ''
  END AS DATA_TYPE_JP
FROM 
  USER_TAB_COLUMNS A
  INNER JOIN USER_COL_COMMENTS B ON (A.TABLE_NAME=B.TABLE_NAME AND A.COLUMN_NAME=B.COLUMN_NAME)
  LEFT JOIN (
    SELECT 
      X.TABLE_NAME,
      Y.COLUMN_NAME,
      X.CONSTRAINT_TYPE
    FROM
      USER_CONSTRAINTS X 
      INNER JOIN USER_CONS_COLUMNS Y
        ON (X.TABLE_NAME=Y.TABLE_NAME AND X.CONSTRAINT_NAME=Y.CONSTRAINT_NAME)
    WHERE
      X.CONSTRAINT_TYPE='P'
  ) C ON (A.TABLE_NAME=C.TABLE_NAME AND A.COLUMN_NAME=C.COLUMN_NAME)
WHERE
  A.TABLE_NAME='CCMENU' AND
  A.DATA_TYPE NOT IN ('LONG','CLOB','INTERVAL YEAR TO MONTH','INTERVAL DAY TO SECOND','RAW','LONG RAW','BLOB','BFILE','ROWID') AND
  A.COLUMN_NAME NOT IN ('INSDATE','INSUSRID','INSPGID','UPDUSRID','UPDPGID','REVISION')
ORDER BY
  A.TABLE_NAME,
  A.COLUMN_ID
  
