■初期化パラメータ(nls_length_semantics)
SELECT NAME,VALUE FROM V$SYSTEM_PARAMETER WHERE NAME = 'nls_length_semantics'

■
select USERNAME, DEFAULT_TABLESPACE from DBA_USERS where ACCOUNT_STATUS='OPEN' and DEFAULT_TABLESPACE<>'SYSTEM' order by USERNAME;
select TABLE_NAME from all_tables where OWNER='PROGNERTEST' and TABLESPACE_NAME='USERS' order by TABLE_NAME;

SELECT
  A.OWNER AS SCHEMA_NAME,
  A.TABLE_NAME
FROM
  ALL_TABLES A INNER JOIN DBA_USERS B ON (A.OWNER=B.USERNAME AND A.TABLESPACE_NAME=B.DEFAULT_TABLESPACE)
WHERE
  A.OWNER='PROGNERTEST' AND
  B.DEFAULT_TABLESPACE<>'SYSTEM'
ORDER BY
  A.OWNER,
  A.TABLE_NAME

■カラム情報
SELECT 
  A.TABLE_NAME,
  A.COLUMN_ID,
  A.COLUMN_NAME,
  A.DATA_TYPE,
  CASE
    WHEN LENGTH(A.DATA_TYPE) < 10 THEN A.DATA_TYPE
    WHEN A.DATA_TYPE = 'BINARY_FLOAT' THEN '数値(FLOAT)'
    WHEN A.DATA_TYPE = 'BINARY_DOUBLE' THEN '数値(DOUBLE)'
    WHEN SUBSTR(A.DATA_TYPE,0,10) = 'TIMESTAMP(' THEN 'TIMESTAMP'
    WHEN A.DATA_TYPE = 'TIMESTAMP WITH TIMEZONE' THEN '日付(TZ)'
    WHEN A.DATA_TYPE = 'TIMESTAMP WITH LOCAL TIMEZONE' THEN '日付(LTZ)'
    WHEN A.DATA_TYPE = 'INTERVAL YEAR TO MONTH' THEN '日付(年,月)'
    WHEN A.DATA_TYPE = 'INTERVAL DAY TO SECOND' THEN '日付(日～秒)'
    ELSE 'その他の型'
  END AS DATA_TYPE_JP,
  CASE
    WHEN C.CONSTRAINT_TYPE='P' THEN 'Y'
    ELSE 'N'
  END AS PRIMARY_KEY,
  A.NULLABLE,
  CASE
    WHEN (C.CONSTRAINT_TYPE='P' OR A.DATA_TYPE NOT IN ('VARCHAR2','NVARCHAR2','CHAR','NCHAR','NUMBER','BINARY_FLOAT','BINARY_DOUBLE','DATE')) AND
      SUBSTR(A.DATA_TYPE,0,9) <> 'TIMESTAMP' THEN 'Y'
    ELSE 'N'
  END AS READ_ONLY,
  A.DATA_LENGTH,
  A.CHAR_COL_DECL_LENGTH,
  A.DATA_PRECISION,
  A.DATA_SCALE,
  CASE
    WHEN A.DATA_TYPE IN ('CHAR','NCHAR','VARCHAR2','NVARCHAR2') THEN GREATEST(LEAST(A.CHAR_COL_DECL_LENGTH,15),5)
    WHEN A.DATA_TYPE IN ('NUMBER','BINARY_FLOAT','BINARY_DOUBLE') THEN GREATEST(A.DATA_PRECISION,15)
    ELSE 15
  END AS COLUMN_WIDTH,
  COALESCE(B.COMMENTS,A.COLUMN_NAME) AS COMMENTS
FROM 
  USER_TAB_COLUMNS A
  INNER JOIN USER_COL_COMMENTS B ON (A.TABLE_NAME=B.TABLE_NAME AND A.COLUMN_NAME=B.COLUMN_NAME)
  LEFT JOIN (
    SELECT 
      X.TABLE_NAME,
      Y.COLUMN_NAME,
      X.CONSTRAINT_TYPE
    FROM
      USER_CONSTRAINTS X 
      INNER JOIN USER_CONS_COLUMNS Y
        ON (X.TABLE_NAME=Y.TABLE_NAME AND X.CONSTRAINT_NAME=Y.CONSTRAINT_NAME)
    WHERE
      X.CONSTRAINT_TYPE='P'
  ) C ON (A.TABLE_NAME=C.TABLE_NAME AND A.COLUMN_NAME=C.COLUMN_NAME)
WHERE
  A.TABLE_NAME='TEST_TABLE2' AND
  A.DATA_TYPE NOT IN ('LONG','CLOB','INTERVAL YEAR TO MONTH','INTERVAL DAY TO SECOND','RAW','LONG RAW','BLOB','BFILE','ROWID') AND
  A.COLUMN_NAME NOT IN ('INSDATE','INSUSRID','INSPGID','UPDUSRID','UPDPGID','REVISION')
ORDER BY
  A.COLUMN_ID
